### PR TITLE
Php 8.1 compatibility

### PR DESCRIPTION
**Pull request by kralmichal**

### CODE REVIEW

**Comment by BenMorel** [comment]
Any update here? PHP 8.1.4 is out, and PHP 8.1 is still not properly supported.

**Comment by bshaffer** [comment]
This repo does not accept pull requests

**Comment by bshaffer** [comment]
Please file an issue with [google-cloud-php](https://github.com/googleapis/google-cloud-php), but this package _should be_ compatible with 8.1

**Comment by bshaffer** [comment]
Yes, you can see both https://github.com/googleapis/google-cloud-php/blob/main/Core/src/Iterator/ItemIteratorTrait.php and https://github.com/googleapis/google-cloud-php/blob/main/Core/src/Iterator/PageIteratorTrait.php have the needed annotation now.

**Pull request closed without merging**
